#----------------------------------------------------------------------------------------------------#
#
# Home Assistant pinga ogni 15 secondi la stampante
#
#----------------------------------------------------------------------------------------------------#
- platform: ping
  scan_interval: 15
  host: !secret ip_stampante
  name: stampante_brother
#----------------------------------------------------------------------------------------------------#
#
# Definiamo i giorni lavorativi o non
#
#----------------------------------------------------------------------------------------------------#
- platform: workday
  country: IT
  workdays: [mon,tue,wed,thu,fri]
  excludes: [sat,sun,holiday]
  add_holidays:
    - '2020-08-31'
    - '2021-08-31'
